name: .NET CI Pipeline (Self-Hosted)

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops
  workflow_dispatch:  

jobs:
  restore:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        
        run: dotnet restore src/PortailRH.sln 

  build:
    runs-on: [self-hosted, Windows, X64]
    needs: restore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: [self-hosted, Windows, X64]
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: [self-hosted, Windows, X64]
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 
      - name: Publish
        run: dotnet publish -c Release -o ./publish


      - name: Upload publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-publish
          path: ./publish
