name: .NET CI Pipeline (Self-Hosted)

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops
  workflow_dispatch:  

jobs:
  restore:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/PortailRH.sln

  build:
    runs-on: [self-hosted, Windows, X64]
    needs: restore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies (again for this job)
        run: dotnet restore src/PortailRH.sln

      - name: Build
        run: dotnet build src/PortailRH.sln --configuration Release --no-restore

  test:
    runs-on: [self-hosted, Windows, X64]
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies (again for this job)
        run: dotnet restore src/PortailRH.sln

      - name: Build (again for this job)
        run: dotnet build src/PortailRH.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test src/PortailRH.sln --no-build --verbosity normal

  publish:
    runs-on: [self-hosted, Windows, X64]
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/PortailRH.sln

      - name: Build
        run: dotnet build src/PortailRH.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/PortailRH.sln -c Release -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: ./publish

  deploy:
      runs-on: [self-hosted, Windows, X64]
      needs: publish
      steps:
        - name: Download published artifact
          uses: actions/download-artifact@v4
          with:

           name: dotnet-publish
           path: ./publish

        - name: Deploy to local folder
          run: |
            $target = "D:\Apps\PortailRH"   # <-- mets ton chemin réel ici
            if (Test-Path $target) { Remove-Item "$target\*" -Recurse -Force }
            Copy-Item -Path "./publish/*" -Destination $target -Recurse
            Write-Host "✅ Application déployée dans $target"